name: Docker Build
on:
  pull_request:
    branches:
      - development

jobs:
  build:
    strategy:
      matrix:
        service: ['api-service']
    name: Build ${{ matrix.service }} docker image
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker build \
          -f apps/${{ matrix.service }}/Dockerfile . \
          -t ${{ github.repository }}/${{ matrix.service }}:${{ github.sha }}