name: Docker Build
on:
  pull_request:
    branches:
      - development

jobs:
  build:
    name: Build ${{ matrix.service }} docker image
    strategy:
      matrix:
        service: ['api-service']
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 8

      - name: Build docker image
        run: |
          docker build \
          -f apps/${{ matrix.service }}/Dockerfile . \
          -t ${{ github.repository }}/${{ matrix.service }}:${{ steps.short-sha.outputs.sha }}

      - name: Docker Images
        run: docker images